# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{reporter}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthijs Groen"]
  s.date = %q{2010-09-16}
  s.description = %q{
      Reporter adds a consistent way to build reports.
    }
  s.email = %q{matthijs.groen@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/reporter/data_set.rb",
     "lib/reporter/data_source.rb",
     "lib/reporter/data_source/active_record_source.rb",
     "lib/reporter/data_source/scoping.rb",
     "lib/reporter/data_structure.rb",
     "lib/reporter/field/average_field.rb",
     "lib/reporter/field/base.rb",
     "lib/reporter/field/calculation_field.rb",
     "lib/reporter/field/count_field.rb",
     "lib/reporter/field/field.rb",
     "lib/reporter/field/formula_field.rb",
     "lib/reporter/field/sum_field.rb",
     "lib/reporter/formula.rb",
     "lib/reporter/result_row.rb",
     "lib/reporter/scope/base.rb",
     "lib/reporter/scope/date_scope.rb",
     "lib/reporter/scope/reference_scope.rb",
     "lib/reporter/support/time_range.rb",
     "lib/reporter/time_iterator.rb",
     "lib/reporter/time_optimized_result_row.rb",
     "lib/reporter/value.rb"
  ]
  s.homepage = %q{http://github.com/matthijsgroen/reporter}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Report builder.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<arel>, ["~> 1.0.1"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<arel>, ["~> 1.0.1"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<arel>, ["~> 1.0.1"])
  end
end

