# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "reporter"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matthijs Groen"]
  s.date = "2011-09-19"
  s.description = "\n      Reporter adds a consistent way to build reports.\n    "
  s.email = "matthijs.groen@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/reporter/data_set.rb",
    "lib/reporter/data_source.rb",
    "lib/reporter/data_source/active_record_source.rb",
    "lib/reporter/data_source/scoping.rb",
    "lib/reporter/data_structure.rb",
    "lib/reporter/field/average_field.rb",
    "lib/reporter/field/base.rb",
    "lib/reporter/field/calculation_field.rb",
    "lib/reporter/field/count_field.rb",
    "lib/reporter/field/field.rb",
    "lib/reporter/field/formula_field.rb",
    "lib/reporter/field/sum_field.rb",
    "lib/reporter/formula.rb",
    "lib/reporter/result_row.rb",
    "lib/reporter/scope/base.rb",
    "lib/reporter/scope/date_scope.rb",
    "lib/reporter/scope/reference_scope.rb",
    "lib/reporter/support/time_range.rb",
    "lib/reporter/time_iterator.rb",
    "lib/reporter/time_optimized_result_row.rb",
    "lib/reporter/value.rb",
    "reporter.gemspec"
  ]
  s.homepage = "http://github.com/matthijsgroen/reporter"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Report builder."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<arel>, [">= 1.0.1"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<arel>, ["~> 1.0.1"])
    else
      s.add_dependency(%q<arel>, [">= 1.0.1"])
      s.add_dependency(%q<activerecord>, ["~> 3.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0"])
      s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<arel>, ["~> 1.0.1"])
    end
  else
    s.add_dependency(%q<arel>, [">= 1.0.1"])
    s.add_dependency(%q<activerecord>, ["~> 3.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0"])
    s.add_dependency(%q<activerecord>, ["~> 3.0.0"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<arel>, ["~> 1.0.1"])
  end
end

